# Project-wide Gradle settings.

# IDE (e.g., Android Studio) users:
# Gradle settings configured via the IDE *will override*
# any settings specified in this file.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=C\:\\Users\\dreyg\\.jdks\\jbr-17.0.14

android.useAndroidX=true
kotlin.code.style=official

# When configured, Gradle will run in incubating parallel mode.
org.gradle.parallel=true

# AndroidX package structure and makes it easier to package versioned libraries
android.nonTransitiveRClass=true

# Use more recent AGP features
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false

# Enabled parallel sync for Gradle 9.7+
org.gradle.tooling.parallel=true

# Allow Kotlin source sets with built-in Kotlin (AGP 9+)